# Generated by Django 4.0.6 on 2022-08-09 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='enter your name', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Enter your age', max_length=50, null=True)),
                ('email', models.EmailField(error_messages={'unique': 'dont fuck with me dud enter valid email'}, help_text='enter your email address', max_length=255, null=True, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], help_text='Enter your gender', max_length=10, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(null=True, upload_to='myapp/uploads')),
                ('image', models.ImageField(null=True, upload_to='myapp/uploads')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.client')),
            ],
            options={
                'verbose_name': 'Person',
            },
        ),
    ]
