# Generated by Django 4.0.6 on 2022-08-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='person_upload',
        ),
    ]
