# Generated by Django 4.0.6 on 2022-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='client_name',
            field=models.CharField(help_text='enter your name', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
