# Generated by Django 4.0.6 on 2022-08-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_student_name_student_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='client_name',
            new_name='name',
        ),
    ]
